### ISSUE TITLE
Credits Issue

### ISSUE THREAD

**Issue by fishyWET** [tenplus1/mobs#10]
Regarding https://github.com/tenplus1/mobs/blob/master/spider.lua#L2
All credits of the spider model goes to AspireMint. I do not have any contributions to it. Please make the necessary adjustments.

Furthermore, the spider model was licensed under CC-BY-SA 3.0, this means, "If you remix, transform, or build upon the material, you must distribute your contributions under the same license as the original". This means there is a need for you to clearly state the spider model is CC BY-SA and by AspireMint.

**Comment by tenplus1** [comment]
done...
