### ISSUE TITLE
Added check for lavaslime to not destroy actual nodes with fire 

### ISSUE THREAD

**Issue by Ombridride** [tenplus1/mobs#13]
- Lavaslimes now check if the node there are trying to place fire instead of
  is air. If it is not, they do not put fire (to avoid detroying nodes)

=> https://github.com/Ombridride/minetest-minetestforfun-server/commit/db8cc41fd7fd997ee84583fc75a83e2e86d6378c

Are you interrested ?

**Comment by tenplus1** [comment]
Added, Thanks...
