### ISSUE TITLE
Question: Why have you made register_mob

### ISSUE THREAD

**Issue by greencopper** [tenplus1/mobs#14]
Hi tenplus1

I wanted to start working on an isolated mobs mod in which I want to collect all useful mobs ever made, isolate each mob from each other and then people can use that simply by removing what ever mob they don't want.

I have found your mobs quite useful, but going through the code made me wonder what's going on.

Why have you made (or perhaps it is based upon something else originally) say the function register_mobs rather than just calling minetest:register_entity directly?

I cannot grasp what exactly is going on.

Kind regards

**Comment by tenplus1** [comment]
Registering an entity is a simple affair but lacks settings and control functions within, register_mob has all of the settings laid out and functions within to handle mob movement, attack etc. for all different mobs instead of 1 only...
