### ISSUE TITLE
Request : Make explosions not affect blast resistant concrete

### ISSUE THREAD

**Issue by pyrollo** [tenplus1/mobs#19]
Hi,
I think that blast resistant concrete from technic mod should not be destroyed by dungeon master explosions. I gave a quick try (with and without technic mod) after applying following modification on api.lua and it works well : 
```
1132a1133
> 	local c_blast = minetest.get_content_id("technic:blast_resistant_concrete")
1151c1152
< 		if data[vi] ~= c_air and data[vi] ~= c_ignore and data[vi] ~= c_obsidian and data[vi] ~= c_brick and data[vi] ~= c_chest then
---
> 		if data[vi] ~= c_air and data[vi] ~= c_ignore and data[vi] ~= c_obsidian and data[vi] ~= c_brick and data[vi] ~= c_chest and data[vi] ~= c_blast then
```
I guess it could be even better to have a group for "non exploding" nodes but I'm not that aware of how to do it yet :)

**Comment by blert2112** [comment]
Might be better to add code to respect a node's on_blast() function instead of hard-coding in a ton of different node types. 

- Chris

**Comment by tenplus1** [comment]
If the blast resistant concrete has the "unbreakable=1" group set then it will not be destroyed by fireballs...  This group was added to save listing each and every node that shouldnt be affected by the blast...
