### ISSUE TITLE
crash if tools(buggy) has not full_punch_interval

### ISSUE THREAD

**Issue by crabman77** [tenplus1/mobs#23]
if tools(buggy?) has not full_punch_interval -->  https://github.com/HybridDog/minetest-nether/blob/master/nether/items.lua#L801

https://github.com/tenplus1/mobs/blob/master/api.lua#L1129 --> api.lua: attempt to perform arithmetic on field 'full_punch_interval' (a nil value)

fix --> https://github.com/Ombridride/minetest-minetestforfun-server/commit/23545d1bc66c87c22ace8fc4a93dbced3e15e8c4

@HybridDog there isn't not buttons issue to report.

**Comment by tenplus1** [comment]
Fixed...
