### ISSUE TITLE
lamb and calf crashing the game

### ISSUE THREAD

**Issue by Xanthin** [tenplus1/mobs#26]
When a lamb/calf is spawned and you move away from it the game crashes with
>2015-08-01 13:39:59: ERROR[main]: ServerError: ...0.4.12-7bbb9b0-win64\bin\..\builtin\common\serialize.lua:152: Can't serialize data of type userdata
>2015-08-01 13:39:59: ERROR[main]: stack traceback:
>2015-08-01 13:39:59: ERROR[main]:    [C]: in function 'error'
>2015-08-01 13:39:59: ERROR[main]:    ...0.4.12-7bbb9b0-win64\bin\..\builtin\common\serialize.lua:152: in function 'dump_or_ref_val'
>2015-08-01 13:39:59: ERROR[main]:    ...0.4.12-7bbb9b0-win64\bin\..\builtin\common\serialize.lua:147: in function 'dump_or_ref_val'
>2015-08-01 13:39:59: ERROR[main]:    ...0.4.12-7bbb9b0-win64\bin\..\builtin\common\serialize.lua:147: in function 'dump_or_ref_val'
>2015-08-01 13:39:59: ERROR[main]:    ...0.4.12-7bbb9b0-win64\bin\..\builtin\common\serialize.lua:167: in function <...0.4.12-7bbb9b0-win64\bin\..\builtin\common\serialize.lua:20>

Mentioned in the [Xanadu topic] (https://forum.minetest.net/viewtopic.php?f=10&t=8494&sid=0177855ddaaa56e728655b309840a350&start=900#p185869)

**Comment by Routhinator** [comment]
Confirming this, It took me a while to nail it down but this has been causing crashes on my server for a couple weeks.

**Comment by tenplus1** [comment]
I've rewritten the self. variable section which may have caused a few glitches in the breeding area but all should be well now...
