### ISSUE TITLE
Some options not configurable

### ISSUE THREAD

**Issue by JohnWayne1986** [tenplus1/mobs#28]
In api.lua there are 3 settings assigned with `... or true`. This will always result in true and makes these options not configurable.
```
line 6:local damage_enabled = minetest.setting_getbool("enable_damage") or true
line 8:local enable_blood = minetest.setting_getbool("mobs_enable_blood") or true
line 53:             jump = def.jump or true,
```
You can replace the `... or true` by `... or false` to be sure to have a boolean. After correction you will notice a difference when you disable in the GUI menu "Enable damage", the mobs won't attack anymore.

**Comment by tenplus1** [comment]
the "or true" section is only there incase minetest.conf does not contain a setting for that value, a default...

**Comment by JohnWayne1986** [comment]
Yes, I understood the purpose, but `... or true` for `...` being a boolean or nil is equivalent to simply `true`. More detailed:

 * `false or true` is `true`
 * `nil or true` is `true`
 * `true or true` is `true`

So you could either replace these right hand sides completely by `true` (then you don't need this variable) or give it a meaning. You have two choices:

 * `... or false` will be the boolean value of `...` (you could also use `not not ...`)
 * `... or ... == nil` will be `...` if it is boolean and `true` if it is nil (undefined). So this gives a default value of `true`.
