### ISSUE TITLE
Error on regular gameplay

### ISSUE THREAD

**Issue by SmallJoker** [tenplus1/mobs#3]
From current HEAD:
```
12:50:41: ERROR[main]: ServerError: E:\Programme\minetest\bin\..\mods\mobs/api.lua:850: attempt t
erform arithmetic on field 'hp_min' (a nil value)
12:50:41: ERROR[main]: stack traceback:
12:50:41: ERROR[main]:  E:\Programme\minetest\bin\..\mods\mobs/api.lua:850: in function <E:\Progr
e\minetest\bin\..\mods\mobs/api.lua:790>
```

**Comment by tenplus1** [comment]
Cannot reproduce error...  What other mods are you running ?

**Comment by SmallJoker** [comment]
base_mobs (mobs from base_game), flatgen, shooter, unified_inventory, worldedit, worldedit_commands

I can reproduce this error within seconds

**Comment by SmallJoker** [comment]
Found the problem. 
This error was caused by spawning a overwritten mob from another mobs mod without the `hp_min` in its definition.
