### ISSUE TITLE
staticdata is lost on respawn mobs

### ISSUE THREAD

**Issue by crabman77** [tenplus1/mobs#30]
when mobs respawn staticdata is lost, collisionbox is wrong.

![screenshot_20150819_022520](https://cloud.githubusercontent.com/assets/7189389/9346674/22f116ec-4620-11e5-958a-22c2249ec73e.png)

after respawn

![screenshot_20150819_022536](https://cloud.githubusercontent.com/assets/7189389/9346575/e56255e4-461e-11e5-8419-681c1a82d8d3.png)

If I remove function get_staticdata() , it's work.
https://github.com/tenplus1/mobs/blob/master/api.lua#L1140
print debug show
===== mobs:npc
{
	env_damage_timer = 15,
	base_mesh = "character.b3d",
	remove_ok = true,
	textures = {
		"mobs_npc.png"
	},
	old_y = 7.5,
	timer = 0,
	base_size = {
		y = 1,
		x = 1
	},
	health = 20,
	mesh = "character.b3d",
	base_texture = {
		"mobs_npc.png"
	},
	order = "stand",
	state = "stand",
	base_colbox = {
		0,
		-1,
		0,
		0,
		0,
		0
	},
	visual_size = {
		y = 1,
		x = 1
	},
	collisionbox = {
		0,
		-1,
		0,
		0,
		0,
		0
	}
}
=====

**Comment by tenplus1** [comment]
I cannot reproduce this error, npc's spawn correctly and collisionbox remains the same when I move far away and return for it to respawn...  What version of minetest are you using ? and what mods are loaded ?

**Comment by crabman77** [comment]
I use 0.4.12-stable version , I just tried on the dev version and it's work .

NPC before|after, param 2 is correct maybe this issue https://github.com/minetest/minetest/issues/2365
collisionbox = {-0.35,-1.0,-0.35, 0.35,0.8,0.35},
collisionbox = {0,-1,0,0,0,0 }

**Comment by crabman77** [comment]
To fixed I rewrite self.collisionbox with def.collisionbox in on_activate() https://github.com/MinetestForFun/minetest-minetestforfun-server/commit/0b6747966fab1102625ac04e7cb4b2b3103bad8d

**Comment by tenplus1** [comment]
Please upgrade to Minetest 0.4.13 and the latest Mobs Redo...  I would not recommend altering the api, especially for server use...
