### ISSUE TITLE
When a mob "dies" from natural causes - eg moving out of range - it leaves "drops"

### ISSUE THREAD

**Issue by eidy** [tenplus1/mobs#34]
When a mob "dies" from natural causes - eg moving out of range - it leaves "drops" without the player having to do anything.

So as the player moves along he comes upon parcels of meat and nyan cats frequently.

IMHO "drops" should only happen if the player kills a mob.

**Comment by tenplus1** [comment]
Mob drops are similar to Minecraft behaviour where they drop items however they die, although if a mob wanders out of range then it is simply removed and has no drops...  This behaviour is handy when using itemflow in my builtin_item mod and collection using hoppers mod...

https://github.com/tenplus1/builtin_item
https://github.com/tenplus1/hopper

**Comment by eidy** [comment]
I understand.    Where this seems rather unnatural however is for monsters that are light sensitive, such as senderman (which I am converting to your new mob framework).

Used in conjunction with the builtin_item mod however, things make much more sense.

 

BTW Great idea with the hoppers mod.
