### ISSUE TITLE
/spawnentity spawned unknown objects

### ISSUE THREAD

**Issue by amadin** [tenplus1/mobs#41]
For example "/spawnentity sheep" will add unknown object.

**Comment by Xanthin** [comment]
You have to use `/spawnentity modname:mobname`. For example `/spawnentity mobs:sheep` (or for its various colors, `mobs:sheep_blue` and so on). Look in the mob's .lua files where `mobs:register_mob("mobs:name", {` is and use that.

**Comment by amadin** [comment]
Thanks.
