### ISSUE TITLE
ERROR[Server]: pathfinder: failed to update cost map

### ISSUE THREAD

**Issue by eidy** [tenplus1/mobs#45]
Hi,

When monsters are running a while (admittedly these are monsters from mods not originally intended for mobs redo such as slimes and senderman) .. with the latest changes I get the following errors when chased pretty frequently: 

2016-02-22 21:11:29: ERROR[Server]: pathfinder: failed to update cost map
2016-02-22 21:11:33: ERROR[Server]: pathfinder: failed to update cost map
2016-02-22 21:11:35: ERROR[Server]: pathfinder: failed to update cost map
2016-02-22 21:11:39: ERROR[Server]: pathfinder: failed to update cost map
2016-02-22 21:11:41: ERROR[Server]: pathfinder: failed to update cost map
2016-02-22 21:11:47: ERROR[Server]: pathfinder: failed to update cost map
2016-02-22 21:11:51: ERROR[Server]: pathfinder: failed to update cost map

Here is ALL the senderman code:

--Senderman

mobs:register_mob("senderman:senderman", {
	type = "monster",
	passive = false,
	attack_type = "dogfight",
	damage = 4,
	hp_min = 3,
	hp_max = 30,
	armor = 80,
	collisionbox = {-0.5, -0.01, -0.5, 0.5, 5.4, 0.5},
	visual_size = {x=8,y=8},
	visual = "mesh",
	mesh = "sender_man.x",
	textures = {
		{"senderman_sender_man.png"},
		{"senderman_sender_man_dark.png"},
	},
	blood_texture = "default_dirt.png",
	makes_footstep_sound = false,
	sounds = {
		random = "senderman_sender_man",
	},
	view_range = 30,
	walk_velocity = 3,
	run_velocity = 6,
	jump = true,
	drops = {
		{name = "default:coal",
		chance = 100, min = 1, max = 1},
	},
	water_damage = 0,
	lava_damage = 0,
	light_damage = 2,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})

mobs:register_spawn("senderman:senderman", {"default:dirt_with_grass", "default:desert_sand"},  3, -1, 9999, 3, 31000)
 
--Egg

minetest.register_craftitem("senderman:senderegg", {
	description = "Spawn Senderman",
	inventory_image = "senderman_egg.png",
	wield_image = inventory_image,
	on_place = function(itemstack, placer, pointed_thing)
		if pointed_thing.above then
			minetest.env:add_entity(pointed_thing.above, "senderman:senderman")
			itemstack:take_item()
		end
		return itemstack
	end,
})

minetest.register_craft({
	output = "senderman:senderegg",
	type = "shapeless",
	recipe = {"spawneggs:egg", "default:nyancat"},
})

--Log

if minetest.setting_get("log_mods") then
	minetest.log("action", "senderman is watching")
end

Hope this helps.

**Comment by tenplus1** [comment]
Thankfully just an error saying the pathfinding routine cannot find a path to the player, it could be from underground monsters and not your slenderman or slime mobs...  You could go into the api.lua and set enable_pathfinding to false to disable them all and the feature.

**Comment by eidy** [comment]
I understand.  In this particular case I was in a tree as senderman
wandered around underneath.
I like pathfinding so I would rather not switch it off.  It's annoying how
the runtime reports it as an "ERROR:" though.

**Comment by tenplus1** [comment]
Am hoping the devs will silence the pathfinding errors unless activated <fingers crossed>
