### ISSUE TITLE
Problem with swimming mobs

### ISSUE THREAD

**Issue by NPXcoot** [tenplus1/mobs#46]
Hi TenPlus1,
there is a problem with the swimming mobs (defined by "fly_in water_source"). In fact even the aggressive swimming mobs can't see you while you are in the water with them and so they don't attack you.
The problem is caused by the fact that the function "minetest.line_of_sight(pos1, pos2, stepsize)" returns false when it finds a block different from "air" between the two positions. This is a function of the core of minetest so we can't modify it, but I've written a workaround for our mod nssm which seems to work.
I defined a new function "line_of_sight_water(pos1, pos2, stepsize)" to be used to determine if the obstacle between the two position is a water block.
I'm attaching here your file api.lua (renamed in api.txt because github doesn't support attaching lua files)
[api.txt](https://github.com/tenplus1/mobs/files/146163/api.txt)
 in which I've added the function and made the code use it (only two changes comparing to your original code: lines 132 and 1114).

Then there is also another small problem related to the first one: now the swimming mobs obviously try to follow you and sometimes they get out of the water and fly around. I've added a call to the method setvelocity to bring them back in the water (line 1354), it is not a so efficient workaround but maybe you can find a better one!
Thank you

**Comment by tenplus1** [comment]
Thanks for bringing this to me attention, I have added the line_of_sight_water function with changes and a few other checks so that swimming mobs do not walk around on land :)  Changes applied.
