### ISSUE TITLE
death sound keeps playing without taking damage and health info is not getting updated

### ISSUE THREAD

**Issue by JurajVajda** [tenplus1/mobs#51]
Hi, i like the new damage system, it just need a bit more fine-tuning ;)

1. The damage sound on function check_on_death() keeps playing also due to do_env_damage() check, probably the health needs to be checked more precisely before playing sound ?

2. there is an immortal group set to 1 which is causing the info text not updating the health while hitting the mob, setting immortal=1 is generally pretty dangerous imho

Could you please check those issues?

Thanks though for your great mobs and the api, i like it very much!

**Comment by tenplus1** [comment]
Setting immortal=1 in armor groups seems the only way to handle special tools that wont harm mobs or can heal them, also I'll soon be adding death animations which is why it is needed most...  As for hurt sounds, I will add a 2nd health variable to compare against.

**Comment by JurajVajda** [comment]
sound good, thanks. :+1:
