### ISSUE TITLE
Add intensity to mob explosion?

### ISSUE THREAD

**Issue by MT-Modder** [tenplus1/mobs#52]
I was going to make a PR but I wanted your opinion on what exactly that intensity would be. The tnt mod uses an intensity of 1.

I personally think an intensity parameter should be added to the explosion function to add flexibility. And the dungeon master explosion should be set to around 0.25 since that seems to be the size relative to a tnt explosion.

What do you think?

**Comment by tenplus1** [comment]
At Xanadu the Dungeon Master's fireball has an explosion intensity of 1 already where the Dungeon Lord (being more powerful) and the Creeper both have an intensity of 2 for their explosions.

**Comment by MT-Modder** [comment]
So just use 1?

That's fine with me, either way. It's really just for other mods that use the intensity parameter in their nodedefs.

And do you want the added parameter in the explosion function so modders can set the intensity for different mobs/attacks?

**Comment by tenplus1** [comment]
Add the pull request and I'll have a look at your changes and include anything handy :)

**Comment by MT-Modder** [comment]
Mmmkay

**Comment by tenplus1** [comment]
Added with changes.
