### ISSUE TITLE
Attempt to call method 'get_armor_groups' (a nil value)

### ISSUE THREAD

**Issue by engineer-pearl** [tenplus1/mobs#55]
Whenever I attack an animal, I get the error
`ERROR: /home/engineer-pearl/.minetest/mobs/api.lua.1861: attempt to call method 'get_armor_groups' (a nil value)
stack traceback:
/home/engineer-pearl/.minetest/mobs/api.lua.1861: in function
</home/engineer-pearl/.minetest/mobs/api.lua.1850>
`

My current mine-test version is 0.4.12, which is the highest version released for my operating system (ubuntu, Wiley), and used a fresh download from your github.

**Comment by tenplus1** [comment]
Hrm, mobs api is slowly being changed to work with Minetest 0.4.13 which is already an old release as 0.4.14 is coming out in the next few weeks...

Here is the link to download Minetest 0.4.13 daily build for your version of ubuntu: https://code.launchpad.net/~minetestdevs/+archive/ubuntu/daily-builds/+sourcepub/6235943/+listing-archive-extra
