### ISSUE TITLE
Could not load image "mobs_sheep_white.png" while building texture

### ISSUE THREAD

**Issue by tchncs** [tenplus1/mobs#57]
```
ERROR[main]: generateImage(): Could not load image "mobs_sheep_white.png" while building texture
ERROR[main] generateImage(): Creating a dummy image for "mobs_sheep_white.png"
```

^ this happends since a few days, since i updated the mod.
On the easter time it was funny but maybe we can back to normal now :)

...doesnt look like just old sheeps, maybe some wrong onces still spawning?
Didn't checked your code until now for time reason... .

**Comment by tenplus1** [comment]
The new coloured sheep setup uses mobs_sheep_base and mobs_sheep_wool textures now so some of the older sheep will display an error looking for the texture file above, picking up sheep and placing back down usually fixes things.
