### ISSUE TITLE
Maybe it can interrest you ?

### ISSUE THREAD

**Issue by Ombridride** [tenplus1/mobs#8]
Hi,

Maybe it can interrest you / give you ideas...

kittens(from Jordach/BFD), wolfs(from mobs_plus), creepers(not from mobf, too slow, the code and api changes are from davedevils), tweaked textures (more textures, and/or more detailled and/or more colorful, more sounds, etc...) : https://github.com/Ombridride/minetest-minetestforfun-server/tree/master/mods/mobs

The "root/base" of this mobs mod is your work, and your work is pretty good ! :) (thank you for your work)

**Comment by tenplus1** [comment]
Kittens added :) already have KPavel's wolf model working and keeping sounds to a minimum to save download size...  Thanks for help :)
