### ISSUE TITLE
api.lua:843: attempt to index a nil value

### ISSUE THREAD

**Issue by Echoes91** [tenplus1/mobs#9]
Running a server with the latest release 1.06, this error happens at random moments:

 23:35:26: ERROR[main]: UNRECOVERABLE error occurred. Stopping server. Please fix the following error:
23:35:26: ERROR[main]: /home/andrea/.minetest/mods/mobs/api.lua:843: attempt to index a nil value
23:35:26: ERROR[main]: stack traceback:
23:35:26: ERROR[main]: 	/home/andrea/.minetest/mods/mobs/api.lua:843: in function </home/andrea/.minetest/mods/mobs/api.lua:817>

Complete traceback: https://bpaste.net/raw/0b5bf75c6c8a

**Comment by tenplus1** [comment]
I cannot recreate this error, can you please tell me which version of minetest you are running and what mods are being used...

**Comment by yo-we** [comment]
Hello tenplus1
We run 0.4.12
We think it might come from "unknown blocks".

**Comment by Echoes91** [comment]
Yes We you must be right, it never happened again into clean worlds where no mod had been deactivated. There must have been some moreores mineral forgotten by the clean mod.

**Comment by yo-we** [comment]
And how to eliminate these (blocks which break the server in fine) in real-time? 
Wouldn't it be better to add some defensive test, as unknown blocks are something that really appears in server life. And it is sure not that expensive in terms of CPU....

**Comment by Echoes91** [comment]
Using the [clean] (https://forum.minetest.net/viewtopic.php?f=11&t=2777&hilit=clean) mod by PilzAdam, you just have to list the old nodes and items/entities and activate it. They should disappear as soon as they're in range.
